### ISSUE TITLE
Nodes cannot be accessed from other threads

### ISSUE THREAD

**Issue by stackoverflow** [tree-sitter/java-tree-sitter#44]
We’ve ran into a wrong thread error, and upon further inspection, we’ve noticed that `Tree` uses an `Arena.ofConfined()` which prevents access from other threads.

Is there any reason why these nodes should not be accessed from other threads? We use multithread extensively in our project and it’s quite cumbersome to funnel all AST node access through a single thread.

**Comment by ObserverOfTime** [comment]
Trees are not thread-safe according to the [tree-sitter API](https://github.com/tree-sitter/tree-sitter/blob/master/lib/include/tree_sitter/api.h#L369-L370).
Is using [`Tree#clone`](https://tree-sitter.github.io/java-tree-sitter/io/github/treesitter/jtreesitter/Tree.html#clone()) on the other thread not an option for you?

**Comment by stackoverflow** [comment]
Oh, I missed the clone method. Will try it out. Thanks!

**Comment by stackoverflow** [comment]
OK. Tried using `clone` but it doesn't seem to work when called from other threads.
Here's a simple Kotlin test to reproduce it.

```kotlin
@Test
fun `Trees can be cloned to other threads`() {
  val code = "foo = 1"

  val parser = Parser(Language(TreeSitterPkl.language()))
  val tree = parser.parse(code).get()
  val exe = Executors.newSingleThreadExecutor()
  exe.submit { tree.clone() }.get()
}
```

Results in:

```
Caused by: java.lang.AssertionError: should not reach here
	at io.github.treesitter.jtreesitter.internal.TreeSitter.ts_tree_copy(TreeSitter.java:1397)
	at io.github.treesitter.jtreesitter.Tree.<init>(Tree.java:31)
	at io.github.treesitter.jtreesitter.Tree.clone(Tree.java:143)
	...
Caused by: java.lang.WrongThreadException: Attempted access outside owning thread
	at java.base/jdk.internal.foreign.MemorySessionImpl.wrongThread(MemorySessionImpl.java:314)
	at java.base/jdk.internal.misc.ScopedMemoryAccess$ScopedAccessError.newRuntimeException(ScopedMemoryAccess.java:113)
	at java.base/jdk.internal.foreign.MemorySessionImpl.checkValidState(MemorySessionImpl.java:209)
	at java.base/jdk.internal.foreign.ConfinedSession.acquire0(ConfinedSession.java:60)
	at io.github.treesitter.jtreesitter.internal.TreeSitter.ts_tree_copy(TreeSitter.java:1395)
	... 8 more
```

**Comment by amaanq** [comment]
> Trees are not thread-safe according to the [tree-sitter API](https://github.com/tree-sitter/tree-sitter/blob/master/lib/include/tree_sitter/api.h#L369-L370). Is using [`Tree#clone`](https://tree-sitter.github.io/java-tree-sitter/io/github/treesitter/jtreesitter/Tree.html#clone()) on the other thread not an option for you?

They're thread-safe for read operations, but not write

**Comment by stackoverflow** [comment]
Having the option for the `parse` method to return a read-only tree, or to make a tree read-only, would be amazing. We only use read operations so they should be already thread-safe.
